spring.application.name=orders-inventory-service
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/f99e2ce1-9cbe-4721-bd63-519d8c893560/v2.0
security.entra.audience=api://1d082e27-d71f-4d06-a680-bfc8967d31e7
