spring.application.name=notifications-audit-service
server.port=8081
spring.kafka.listener.auto-startup=false
spring.data.mongodb.uri=mongodb+srv://cardonosol_db_user:pedidos360@audit.vxbrtc6.mongodb.net/pedidos360_audit?appName=Audit